const bookGenres = [ 'Action and Adventure',
  'Adventure',
  'Anthology',
  'Art',
  'Autobiographies',
  'Biographies',
  'Children\'s',
  'Comic',
  'Comics',
  'Cookbooks',
  'Crime',
  'Diaries',
  'Dictionaries',
  'Docufiction',
  'Drama',
  'Encyclopedias',
  'Epistolary',
  'Erotic',
  'Fantasy',
  'Fiction',
  'Finance',
  'Guide',
  'Health',
  'Historical',
  'History',
  'Horror',
  'Journals',
  'Magic',
  'Math',
  'Mystery',
  'Paranoid',
  'Philosophical',
  'Poetry',
  'Political',
  'Prayer books',
  'Religion, Spirituality & New Age',
  'Romance',
  'Saga',
  'Satire',
  'Science',
  'Science fiction',
  'Self help',
  'Series',
  'Speculative',
  'Superhero',
  'Thriller',
  'Travel',
  'Trilogy',
  'Urban',
  'Western' ];

module.exports = bookGenres;